### .github/workflows/deploy.yml
name: "Terraform Deploy: Cosmos DB"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./azure-cosmos-db
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./azure-cosmos-db
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./azure-cosmos-db
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./azure-cosmos-db